index:
    path: /{trailingSlash}
    controller: App\Controller\IndexController::index
    requirements:
        trailingSlash : "[/]{0,1}"
    defaults:
        trailingSlash : "/"

root:
    path: /{_locale}
    controller: App\Controller\IndexController::index
    defaults:
        _locale: '%locale%'
    options: { i18n: false }

imprint:
    path: /imprint
    controller: App\Controller\SimplePageController::imprint

transparency:
    path: /transparency
    controller: App\Controller\SimplePageController::transparency

charter:
    path: /charter
    controller: App\Controller\SimplePageController::charter

about:
    path: /about-us
    controller: App\Controller\SimplePageController::about

themes:
    path: /themes
    controller: App\Controller\DatasetPageController::themes

people:
    path: /people
    controller: App\Controller\SimplePageController::people

peopleBoard:
    path: /people/board
    controller: App\Controller\DatasetPageController::peopleBoard

peopleStaff:
    path: /people/staff
    controller: App\Controller\DatasetPageController::peopleStaff

# this could be the Styleguide base if anybody ever finishes this
# templates:
#     path: /templates{path}
#     controller: App\Controller\TemplatesController::preview
#     # allow slashes in route parameters, see
#     # https://symfony.com/doc/current/routing/slash_in_parameter.html
#     requirements:
#         path: .+
